-- 021_ncaa_full_division_i_pool.sql
-- Expand men's NCAA assets to all 365 Division I teams for 2026-27.
-- Preserve 2026 tournament scores; non-tournament teams receive 0 historical points.

update public.assets set name='Cal Baptist', external_key='cal-baptist', active=true where sport='NCAA' and name='California Baptist';
update public.assets set name='Connecticut', external_key='connecticut', active=true where sport='NCAA' and name='UConn';
update public.assets set name='Kennesaw St.', external_key='kennesaw-st', active=true where sport='NCAA' and name='Kennesaw State';
update public.assets set name='McNeese St.', external_key='mcneese-st', active=true where sport='NCAA' and name='McNeese';
update public.assets set name='Miami FL', external_key='miami-fl', active=true where sport='NCAA' and name='Miami (FL)';
update public.assets set name='Miami OH', external_key='miami-oh', active=true where sport='NCAA' and name='Miami (Ohio)';
update public.assets set name='Michigan St.', external_key='michigan-st', active=true where sport='NCAA' and name='Michigan State';
update public.assets set name='N.C. State', external_key='n-c-state', active=true where sport='NCAA' and name='NC State';
update public.assets set name='North Dakota St.', external_key='north-dakota-st', active=true where sport='NCAA' and name='North Dakota State';
update public.assets set name='Ohio St.', external_key='ohio-st', active=true where sport='NCAA' and name='Ohio State';
update public.assets set name='Queens', external_key='queens', active=true where sport='NCAA' and name='Queens (N.C.)';
update public.assets set name='Tennessee St.', external_key='tennessee-st', active=true where sport='NCAA' and name='Tennessee State';
update public.assets set name='Utah St.', external_key='utah-st', active=true where sport='NCAA' and name='Utah State';
update public.assets set name='Wright St.', external_key='wright-st', active=true where sport='NCAA' and name='Wright State';
update public.assets set name='Texas A&M', external_key='texas-a-m', active=true where sport='NCAA' and name='Texas A&M';
update public.assets set name='Prairie View A&M', external_key='prairie-view-a-m', active=true where sport='NCAA' and name='Prairie View A&M';
update public.assets set name='LIU', external_key='liu', active=true where sport='NCAA' and name='LIU';
update public.assets set name='Saint Louis', external_key='saint-louis', active=true where sport='NCAA' and name='Saint Louis';
update public.assets set name='Saint Mary''s', external_key='saint-mary-s', active=true where sport='NCAA' and name='Saint Mary''s';
update public.assets set name='St. John''s', external_key='st-john-s', active=true where sport='NCAA' and name='St. John''s';

insert into public.assets(sport,external_key,name,asset_type,active)
values
('NCAA','duke','Duke','TEAM',true),
('NCAA','michigan','Michigan','TEAM',true),
('NCAA','florida','Florida','TEAM',true),
('NCAA','arizona','Arizona','TEAM',true),
('NCAA','houston','Houston','TEAM',true),
('NCAA','illinois','Illinois','TEAM',true),
('NCAA','iowa-st','Iowa St.','TEAM',true),
('NCAA','purdue','Purdue','TEAM',true),
('NCAA','connecticut','Connecticut','TEAM',true),
('NCAA','michigan-st','Michigan St.','TEAM',true),
('NCAA','texas-tech','Texas Tech','TEAM',true),
('NCAA','gonzaga','Gonzaga','TEAM',true),
('NCAA','tennessee','Tennessee','TEAM',true),
('NCAA','louisville','Louisville','TEAM',true),
('NCAA','vanderbilt','Vanderbilt','TEAM',true),
('NCAA','alabama','Alabama','TEAM',true),
('NCAA','nebraska','Nebraska','TEAM',true),
('NCAA','kansas','Kansas','TEAM',true),
('NCAA','virginia','Virginia','TEAM',true),
('NCAA','arkansas','Arkansas','TEAM',true),
('NCAA','st-john-s','St. John''s','TEAM',true),
('NCAA','wisconsin','Wisconsin','TEAM',true),
('NCAA','ohio-st','Ohio St.','TEAM',true),
('NCAA','saint-mary-s','Saint Mary''s','TEAM',true),
('NCAA','iowa','Iowa','TEAM',true),
('NCAA','north-carolina','North Carolina','TEAM',true),
('NCAA','ucla','UCLA','TEAM',true),
('NCAA','santa-clara','Santa Clara','TEAM',true),
('NCAA','clemson','Clemson','TEAM',true),
('NCAA','cincinnati','Cincinnati','TEAM',true),
('NCAA','villanova','Villanova','TEAM',true),
('NCAA','texas-a-m','Texas A&M','TEAM',true),
('NCAA','kentucky','Kentucky','TEAM',true),
('NCAA','miami-fl','Miami FL','TEAM',true),
('NCAA','utah-st','Utah St.','TEAM',true),
('NCAA','georgia','Georgia','TEAM',true),
('NCAA','indiana','Indiana','TEAM',true),
('NCAA','byu','BYU','TEAM',true),
('NCAA','n-c-state','N.C. State','TEAM',true),
('NCAA','saint-louis','Saint Louis','TEAM',true),
('NCAA','smu','SMU','TEAM',true),
('NCAA','auburn','Auburn','TEAM',true),
('NCAA','san-diego-st','San Diego St.','TEAM',true),
('NCAA','missouri','Missouri','TEAM',true),
('NCAA','texas','Texas','TEAM',true),
('NCAA','oklahoma','Oklahoma','TEAM',true),
('NCAA','baylor','Baylor','TEAM',true),
('NCAA','tcu','TCU','TEAM',true),
('NCAA','washington','Washington','TEAM',true),
('NCAA','new-mexico','New Mexico','TEAM',true),
('NCAA','south-florida','South Florida','TEAM',true),
('NCAA','vcu','VCU','TEAM',true),
('NCAA','grand-canyon','Grand Canyon','TEAM',true),
('NCAA','ucf','UCF','TEAM',true),
('NCAA','virginia-tech','Virginia Tech','TEAM',true),
('NCAA','florida-st','Florida St.','TEAM',true),
('NCAA','boise-st','Boise St.','TEAM',true),
('NCAA','minnesota','Minnesota','TEAM',true),
('NCAA','tulsa','Tulsa','TEAM',true),
('NCAA','stanford','Stanford','TEAM',true),
('NCAA','seton-hall','Seton Hall','TEAM',true),
('NCAA','northwestern','Northwestern','TEAM',true),
('NCAA','arizona-st','Arizona St.','TEAM',true),
('NCAA','west-virginia','West Virginia','TEAM',true),
('NCAA','akron','Akron','TEAM',true),
('NCAA','usc','USC','TEAM',true),
('NCAA','wake-forest','Wake Forest','TEAM',true),
('NCAA','california','California','TEAM',true),
('NCAA','northern-iowa','Northern Iowa','TEAM',true),
('NCAA','lsu','LSU','TEAM',true),
('NCAA','providence','Providence','TEAM',true),
('NCAA','butler','Butler','TEAM',true),
('NCAA','mcneese-st','McNeese St.','TEAM',true),
('NCAA','nevada','Nevada','TEAM',true),
('NCAA','colorado','Colorado','TEAM',true),
('NCAA','oklahoma-st','Oklahoma St.','TEAM',true),
('NCAA','marquette','Marquette','TEAM',true),
('NCAA','belmont','Belmont','TEAM',true),
('NCAA','dayton','Dayton','TEAM',true),
('NCAA','mississippi','Mississippi','TEAM',true),
('NCAA','syracuse','Syracuse','TEAM',true),
('NCAA','georgetown','Georgetown','TEAM',true),
('NCAA','george-washington','George Washington','TEAM',true),
('NCAA','creighton','Creighton','TEAM',true),
('NCAA','miami-oh','Miami OH','TEAM',true),
('NCAA','wichita-st','Wichita St.','TEAM',true),
('NCAA','utah-valley','Utah Valley','TEAM',true),
('NCAA','colorado-st','Colorado St.','TEAM',true),
('NCAA','stephen-f-austin','Stephen F. Austin','TEAM',true),
('NCAA','yale','Yale','TEAM',true),
('NCAA','hofstra','Hofstra','TEAM',true),
('NCAA','oregon','Oregon','TEAM',true),
('NCAA','xavier','Xavier','TEAM',true),
('NCAA','high-point','High Point','TEAM',true),
('NCAA','davidson','Davidson','TEAM',true),
('NCAA','saint-joseph-s','Saint Joseph''s','TEAM',true),
('NCAA','wyoming','Wyoming','TEAM',true),
('NCAA','notre-dame','Notre Dame','TEAM',true),
('NCAA','mississippi-st','Mississippi St.','TEAM',true),
('NCAA','cal-baptist','Cal Baptist','TEAM',true),
('NCAA','depaul','DePaul','TEAM',true),
('NCAA','south-carolina','South Carolina','TEAM',true),
('NCAA','pittsburgh','Pittsburgh','TEAM',true),
('NCAA','kansas-st','Kansas St.','TEAM',true),
('NCAA','sam-houston-st','Sam Houston St.','TEAM',true),
('NCAA','seattle','Seattle','TEAM',true),
('NCAA','pacific','Pacific','TEAM',true),
('NCAA','unlv','UNLV','TEAM',true),
('NCAA','illinois-chicago','Illinois Chicago','TEAM',true),
('NCAA','uc-irvine','UC Irvine','TEAM',true),
('NCAA','illinois-st','Illinois St.','TEAM',true),
('NCAA','st-thomas','St. Thomas','TEAM',true),
('NCAA','maryland','Maryland','TEAM',true),
('NCAA','north-dakota-st','North Dakota St.','TEAM',true),
('NCAA','george-mason','George Mason','TEAM',true),
('NCAA','utah','Utah','TEAM',true),
('NCAA','rutgers','Rutgers','TEAM',true),
('NCAA','ut-rio-grande-valley','UT Rio Grande Valley','TEAM',true),
('NCAA','liberty','Liberty','TEAM',true),
('NCAA','hawaii','Hawaii','TEAM',true),
('NCAA','uc-san-diego','UC San Diego','TEAM',true),
('NCAA','florida-atlantic','Florida Atlantic','TEAM',true),
('NCAA','san-francisco','San Francisco','TEAM',true),
('NCAA','unc-wilmington','UNC Wilmington','TEAM',true),
('NCAA','washington-st','Washington St.','TEAM',true),
('NCAA','uc-santa-barbara','UC Santa Barbara','TEAM',true),
('NCAA','duquesne','Duquesne','TEAM',true),
('NCAA','montana-st','Montana St.','TEAM',true),
('NCAA','southern-illinois','Southern Illinois','TEAM',true),
('NCAA','wright-st','Wright St.','TEAM',true),
('NCAA','fresno-st','Fresno St.','TEAM',true),
('NCAA','memphis','Memphis','TEAM',true),
('NCAA','bradley','Bradley','TEAM',true),
('NCAA','murray-st','Murray St.','TEAM',true),
('NCAA','uab','UAB','TEAM',true),
('NCAA','idaho','Idaho','TEAM',true),
('NCAA','boston-college','Boston College','TEAM',true),
('NCAA','northern-colorado','Northern Colorado','TEAM',true),
('NCAA','toledo','Toledo','TEAM',true),
('NCAA','penn-st','Penn St.','TEAM',true),
('NCAA','troy','Troy','TEAM',true),
('NCAA','temple','Temple','TEAM',true),
('NCAA','middle-tennessee','Middle Tennessee','TEAM',true),
('NCAA','rhode-island','Rhode Island','TEAM',true),
('NCAA','central-arkansas','Central Arkansas','TEAM',true),
('NCAA','arkansas-st','Arkansas St.','TEAM',true),
('NCAA','navy','Navy','TEAM',true),
('NCAA','north-texas','North Texas','TEAM',true),
('NCAA','cornell','Cornell','TEAM',true),
('NCAA','bowling-green','Bowling Green','TEAM',true),
('NCAA','loyola-marymount','Loyola Marymount','TEAM',true),
('NCAA','uc-davis','UC Davis','TEAM',true),
('NCAA','eastern-washington','Eastern Washington','TEAM',true),
('NCAA','robert-morris','Robert Morris','TEAM',true),
('NCAA','penn','Penn','TEAM',true),
('NCAA','portland-st','Portland St.','TEAM',true),
('NCAA','harvard','Harvard','TEAM',true),
('NCAA','st-bonaventure','St. Bonaventure','TEAM',true),
('NCAA','austin-peay','Austin Peay','TEAM',true),
('NCAA','valparaiso','Valparaiso','TEAM',true),
('NCAA','william-mary','William & Mary','TEAM',true),
('NCAA','georgia-tech','Georgia Tech','TEAM',true),
('NCAA','cal-st-northridge','Cal St. Northridge','TEAM',true),
('NCAA','kent-st','Kent St.','TEAM',true),
('NCAA','montana','Montana','TEAM',true),
('NCAA','western-kentucky','Western Kentucky','TEAM',true),
('NCAA','kennesaw-st','Kennesaw St.','TEAM',true),
('NCAA','oregon-st','Oregon St.','TEAM',true),
('NCAA','merrimack','Merrimack','TEAM',true),
('NCAA','richmond','Richmond','TEAM',true),
('NCAA','monmouth','Monmouth','TEAM',true),
('NCAA','winthrop','Winthrop','TEAM',true),
('NCAA','fordham','Fordham','TEAM',true),
('NCAA','massachusetts','Massachusetts','TEAM',true),
('NCAA','towson','Towson','TEAM',true),
('NCAA','fiu','FIU','TEAM',true),
('NCAA','charlotte','Charlotte','TEAM',true),
('NCAA','oakland','Oakland','TEAM',true),
('NCAA','northern-kentucky','Northern Kentucky','TEAM',true),
('NCAA','green-bay','Green Bay','TEAM',true),
('NCAA','texas-a-m-corpus-chris','Texas A&M Corpus Chris','TEAM',true),
('NCAA','ut-arlington','UT Arlington','TEAM',true),
('NCAA','siena','Siena','TEAM',true),
('NCAA','appalachian-st','Appalachian St.','TEAM',true),
('NCAA','utah-tech','Utah Tech','TEAM',true),
('NCAA','umbc','UMBC','TEAM',true),
('NCAA','campbell','Campbell','TEAM',true),
('NCAA','detroit-mercy','Detroit Mercy','TEAM',true),
('NCAA','portland','Portland','TEAM',true),
('NCAA','charleston','Charleston','TEAM',true),
('NCAA','missouri-st','Missouri St.','TEAM',true),
('NCAA','east-tennessee-st','East Tennessee St.','TEAM',true),
('NCAA','furman','Furman','TEAM',true),
('NCAA','new-mexico-st','New Mexico St.','TEAM',true),
('NCAA','youngstown-st','Youngstown St.','TEAM',true),
('NCAA','tulane','Tulane','TEAM',true),
('NCAA','south-alabama','South Alabama','TEAM',true),
('NCAA','queens','Queens','TEAM',true),
('NCAA','drexel','Drexel','TEAM',true),
('NCAA','new-orleans','New Orleans','TEAM',true),
('NCAA','cal-st-fullerton','Cal St. Fullerton','TEAM',true),
('NCAA','howard','Howard','TEAM',true),
('NCAA','jacksonville-st','Jacksonville St.','TEAM',true),
('NCAA','weber-st','Weber St.','TEAM',true),
('NCAA','columbia','Columbia','TEAM',true),
('NCAA','louisiana-tech','Louisiana Tech','TEAM',true),
('NCAA','indiana-st','Indiana St.','TEAM',true),
('NCAA','marist','Marist','TEAM',true),
('NCAA','mercer','Mercer','TEAM',true),
('NCAA','james-madison','James Madison','TEAM',true),
('NCAA','marshall','Marshall','TEAM',true),
('NCAA','rice','Rice','TEAM',true),
('NCAA','la-salle','La Salle','TEAM',true),
('NCAA','san-diego','San Diego','TEAM',true),
('NCAA','drake','Drake','TEAM',true),
('NCAA','san-jose-st','San Jose St.','TEAM',true),
('NCAA','cal-poly','Cal Poly','TEAM',true),
('NCAA','tennessee-st','Tennessee St.','TEAM',true),
('NCAA','quinnipiac','Quinnipiac','TEAM',true),
('NCAA','south-dakota-st','South Dakota St.','TEAM',true),
('NCAA','buffalo','Buffalo','TEAM',true),
('NCAA','western-carolina','Western Carolina','TEAM',true),
('NCAA','southern-miss','Southern Miss','TEAM',true),
('NCAA','ohio','Ohio','TEAM',true),
('NCAA','bethune-cookman','Bethune Cookman','TEAM',true),
('NCAA','tarleton-st','Tarleton St.','TEAM',true),
('NCAA','stony-brook','Stony Brook','TEAM',true),
('NCAA','texas-st','Texas St.','TEAM',true),
('NCAA','georgia-southern','Georgia Southern','TEAM',true),
('NCAA','coastal-carolina','Coastal Carolina','TEAM',true),
('NCAA','denver','Denver','TEAM',true),
('NCAA','samford','Samford','TEAM',true),
('NCAA','lipscomb','Lipscomb','TEAM',true),
('NCAA','liu','LIU','TEAM',true),
('NCAA','old-dominion','Old Dominion','TEAM',true),
('NCAA','eastern-michigan','Eastern Michigan','TEAM',true),
('NCAA','florida-gulf-coast','Florida Gulf Coast','TEAM',true),
('NCAA','nebraska-omaha','Nebraska Omaha','TEAM',true),
('NCAA','saint-peter-s','Saint Peter''s','TEAM',true),
('NCAA','radford','Radford','TEAM',true),
('NCAA','long-beach-st','Long Beach St.','TEAM',true),
('NCAA','southern','Southern','TEAM',true),
('NCAA','american','American','TEAM',true),
('NCAA','iona','Iona','TEAM',true),
('NCAA','boston-university','Boston University','TEAM',true),
('NCAA','central-michigan','Central Michigan','TEAM',true),
('NCAA','colgate','Colgate','TEAM',true),
('NCAA','princeton','Princeton','TEAM',true),
('NCAA','nicholls-st','Nicholls St.','TEAM',true),
('NCAA','abilene-christian','Abilene Christian','TEAM',true),
('NCAA','lamar','Lamar','TEAM',true),
('NCAA','southeast-missouri-st','Southeast Missouri St.','TEAM',true),
('NCAA','charleston-southern','Charleston Southern','TEAM',true),
('NCAA','vermont','Vermont','TEAM',true),
('NCAA','uc-riverside','UC Riverside','TEAM',true),
('NCAA','unc-asheville','UNC Asheville','TEAM',true),
('NCAA','fairfield','Fairfield','TEAM',true),
('NCAA','pepperdine','Pepperdine','TEAM',true),
('NCAA','siu-edwardsville','SIU Edwardsville','TEAM',true),
('NCAA','east-carolina','East Carolina','TEAM',true),
('NCAA','idaho-st','Idaho St.','TEAM',true),
('NCAA','southern-utah','Southern Utah','TEAM',true),
('NCAA','tennessee-martin','Tennessee Martin','TEAM',true),
('NCAA','elon','Elon','TEAM',true),
('NCAA','purdue-fort-wayne','Purdue Fort Wayne','TEAM',true),
('NCAA','north-dakota','North Dakota','TEAM',true),
('NCAA','wofford','Wofford','TEAM',true),
('NCAA','sacramento-st','Sacramento St.','TEAM',true),
('NCAA','dartmouth','Dartmouth','TEAM',true),
('NCAA','longwood','Longwood','TEAM',true),
('NCAA','lindenwood','Lindenwood','TEAM',true),
('NCAA','utep','UTEP','TEAM',true),
('NCAA','milwaukee','Milwaukee','TEAM',true),
('NCAA','incarnate-word','Incarnate Word','TEAM',true),
('NCAA','delaware','Delaware','TEAM',true),
('NCAA','mount-st-mary-s','Mount St. Mary''s','TEAM',true),
('NCAA','loyola-chicago','Loyola Chicago','TEAM',true),
('NCAA','south-dakota','South Dakota','TEAM',true),
('NCAA','ball-st','Ball St.','TEAM',true),
('NCAA','western-michigan','Western Michigan','TEAM',true),
('NCAA','presbyterian','Presbyterian','TEAM',true),
('NCAA','mercyhurst','Mercyhurst','TEAM',true),
('NCAA','lehigh','Lehigh','TEAM',true),
('NCAA','jacksonville','Jacksonville','TEAM',true),
('NCAA','louisiana','Louisiana','TEAM',true),
('NCAA','brown','Brown','TEAM',true),
('NCAA','arkansas-pine-bluff','Arkansas Pine Bluff','TEAM',true),
('NCAA','unc-greensboro','UNC Greensboro','TEAM',true),
('NCAA','morehead-st','Morehead St.','TEAM',true),
('NCAA','florida-a-m','Florida A&M','TEAM',true),
('NCAA','iu-indy','IU Indy','TEAM',true),
('NCAA','northeastern','Northeastern','TEAM',true),
('NCAA','east-texas-a-m','East Texas A&M','TEAM',true),
('NCAA','sacred-heart','Sacred Heart','TEAM',true),
('NCAA','southeastern-louisiana','Southeastern Louisiana','TEAM',true),
('NCAA','west-georgia','West Georgia','TEAM',true),
('NCAA','alabama-a-m','Alabama A&M','TEAM',true),
('NCAA','bellarmine','Bellarmine','TEAM',true),
('NCAA','eastern-kentucky','Eastern Kentucky','TEAM',true),
('NCAA','grambling-st','Grambling St.','TEAM',true),
('NCAA','oral-roberts','Oral Roberts','TEAM',true),
('NCAA','evansville','Evansville','TEAM',true),
('NCAA','hampton','Hampton','TEAM',true),
('NCAA','texas-southern','Texas Southern','TEAM',true),
('NCAA','usc-upstate','USC Upstate','TEAM',true),
('NCAA','northwestern-st','Northwestern St.','TEAM',true),
('NCAA','prairie-view-a-m','Prairie View A&M','TEAM',true),
('NCAA','stetson','Stetson','TEAM',true),
('NCAA','alabama-st','Alabama St.','TEAM',true),
('NCAA','houston-christian','Houston Christian','TEAM',true),
('NCAA','north-carolina-a-t','North Carolina A&T','TEAM',true),
('NCAA','central-connecticut','Central Connecticut','TEAM',true),
('NCAA','chattanooga','Chattanooga','TEAM',true),
('NCAA','le-moyne','Le Moyne','TEAM',true),
('NCAA','cleveland-st','Cleveland St.','TEAM',true),
('NCAA','georgia-st','Georgia St.','TEAM',true),
('NCAA','wagner','Wagner','TEAM',true),
('NCAA','northern-arizona','Northern Arizona','TEAM',true),
('NCAA','albany','Albany','TEAM',true),
('NCAA','umass-lowell','UMass Lowell','TEAM',true),
('NCAA','lafayette','Lafayette','TEAM',true),
('NCAA','njit','NJIT','TEAM',true),
('NCAA','tennessee-tech','Tennessee Tech','TEAM',true),
('NCAA','loyola-md','Loyola MD','TEAM',true),
('NCAA','bucknell','Bucknell','TEAM',true),
('NCAA','little-rock','Little Rock','TEAM',true),
('NCAA','cal-st-bakersfield','Cal St. Bakersfield','TEAM',true),
('NCAA','north-florida','North Florida','TEAM',true),
('NCAA','norfolk-st','Norfolk St.','TEAM',true),
('NCAA','new-haven','New Haven','TEAM',true),
('NCAA','eastern-illinois','Eastern Illinois','TEAM',true),
('NCAA','holy-cross','Holy Cross','TEAM',true),
('NCAA','jackson-st','Jackson St.','TEAM',true),
('NCAA','niagara','Niagara','TEAM',true),
('NCAA','manhattan','Manhattan','TEAM',true),
('NCAA','stonehill','Stonehill','TEAM',true),
('NCAA','utsa','UTSA','TEAM',true),
('NCAA','fairleigh-dickinson','Fairleigh Dickinson','TEAM',true),
('NCAA','north-alabama','North Alabama','TEAM',true),
('NCAA','army','Army','TEAM',true),
('NCAA','chicago-st','Chicago St.','TEAM',true),
('NCAA','northern-illinois','Northern Illinois','TEAM',true),
('NCAA','air-force','Air Force','TEAM',true),
('NCAA','canisius','Canisius','TEAM',true),
('NCAA','southern-indiana','Southern Indiana','TEAM',true),
('NCAA','alcorn-st','Alcorn St.','TEAM',true),
('NCAA','the-citadel','The Citadel','TEAM',true),
('NCAA','louisiana-monroe','Louisiana Monroe','TEAM',true),
('NCAA','maine','Maine','TEAM',true),
('NCAA','new-hampshire','New Hampshire','TEAM',true),
('NCAA','saint-francis','Saint Francis','TEAM',true),
('NCAA','morgan-st','Morgan St.','TEAM',true),
('NCAA','north-carolina-central','North Carolina Central','TEAM',true),
('NCAA','south-carolina-st','South Carolina St.','TEAM',true),
('NCAA','bryant','Bryant','TEAM',true),
('NCAA','maryland-eastern-shore','Maryland Eastern Shore','TEAM',true),
('NCAA','binghamton','Binghamton','TEAM',true),
('NCAA','rider','Rider','TEAM',true),
('NCAA','vmi','VMI','TEAM',true),
('NCAA','umkc','UMKC','TEAM',true),
('NCAA','gardner-webb','Gardner Webb','TEAM',true),
('NCAA','delaware-st','Delaware St.','TEAM',true),
('NCAA','coppin-st','Coppin St.','TEAM',true),
('NCAA','western-illinois','Western Illinois','TEAM',true),
('NCAA','mississippi-valley-st','Mississippi Valley St.','TEAM',true)
on conflict (sport,external_key) do update
set name=excluded.name, asset_type='TEAM', active=true;

insert into public.competition_editions(sport,label,status,source_ref,starts_on,ends_on)
values(
  'NCAA','2026-27','ACTIVE',
  'https://basketball.realgm.com/ncaa/teams',
  '2026-11-01','2027-04-05'
)
on conflict (sport,label) do update
set status='ACTIVE',source_ref=excluded.source_ref,starts_on=excluded.starts_on,ends_on=excluded.ends_on;

insert into public.competition_entries(edition_id,asset_id,draftable,entry_status,source_ref)
select e.id,a.id,true,'CONFIRMED',e.source_ref
from public.competition_editions e
join public.assets a on a.sport='NCAA' and a.active=true
where e.sport='NCAA' and e.label='2026-27'
on conflict (edition_id,asset_id) do update
set draftable=true,entry_status='CONFIRMED',source_ref=excluded.source_ref;

insert into public.asset_season_stats(asset_id,season_label,scoring_version,points,rank,source_ref,breakdown)
select
  a.id,'2026','v1.2',0,null,
  'https://www.ncaa.com/march-madness-live/bracket',
  jsonb_build_object('tournament_wins',0,'champion',false,'made_tournament',false)
from public.assets a
where a.sport='NCAA' and a.active=true
on conflict (asset_id,season_label,scoring_version) do nothing;

with ranked as (
  select ass.id as stat_id, rank() over(order by ass.points desc)::int as calculated_rank
  from public.asset_season_stats ass
  join public.assets a on a.id=ass.asset_id
  where a.sport='NCAA' and a.active=true
    and ass.season_label='2026' and ass.scoring_version='v1.2'
)
update public.asset_season_stats ass
set rank=ranked.calculated_rank,updated_at=now()
from ranked where ranked.stat_id=ass.id;
