-- 025_f1_2025_historical_scores.sql
insert into public.asset_season_stats(asset_id,season_label,scoring_version,points,rank,source_ref,breakdown)
values
((select id from public.assets where sport='F1' and external_key='lando-norris'),'2025','v1.2',722.22,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',423,'wdc_position',1,'theoretical_max_points',648,'race_sprint_points',522.22,'wdc_placement_points',150,'champion_bonus',50)),
((select id from public.assets where sport='F1' and external_key='max-verstappen'),'2025','v1.2',647.25,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',421,'wdc_position',2,'theoretical_max_points',648,'race_sprint_points',519.75,'wdc_placement_points',127.5,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='oscar-piastri'),'2025','v1.2',614.92,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',410,'wdc_position',3,'theoretical_max_points',648,'race_sprint_points',506.17,'wdc_placement_points',108.75,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='george-russell'),'2025','v1.2',483.83,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',319,'wdc_position',4,'theoretical_max_points',648,'race_sprint_points',393.83,'wdc_placement_points',90,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='charles-leclerc'),'2025','v1.2',373.77,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',242,'wdc_position',5,'theoretical_max_points',648,'race_sprint_points',298.77,'wdc_placement_points',75,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='lewis-hamilton'),'2025','v1.2',252.59,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',156,'wdc_position',6,'theoretical_max_points',648,'race_sprint_points',192.59,'wdc_placement_points',60,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='kimi-antonelli'),'2025','v1.2',230.19,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',150,'wdc_position',7,'theoretical_max_points',648,'race_sprint_points',185.19,'wdc_placement_points',45,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='alex-albon'),'2025','v1.2',123.87,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',73,'wdc_position',8,'theoretical_max_points',648,'race_sprint_points',90.12,'wdc_placement_points',33.75,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='carlos-sainz'),'2025','v1.2',101.51,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',64,'wdc_position',9,'theoretical_max_points',648,'race_sprint_points',79.01,'wdc_placement_points',22.5,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='fernando-alonso'),'2025','v1.2',84.14,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',56,'wdc_position',10,'theoretical_max_points',648,'race_sprint_points',69.14,'wdc_placement_points',15,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='nico-hulkenberg'),'2025','v1.2',62.96,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',51,'wdc_position',11,'theoretical_max_points',648,'race_sprint_points',62.96,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='isack-hadjar'),'2025','v1.2',62.96,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',51,'wdc_position',12,'theoretical_max_points',648,'race_sprint_points',62.96,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='oliver-bearman'),'2025','v1.2',50.62,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',41,'wdc_position',13,'theoretical_max_points',648,'race_sprint_points',50.62,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='liam-lawson'),'2025','v1.2',46.91,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',38,'wdc_position',14,'theoretical_max_points',648,'race_sprint_points',46.91,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='esteban-ocon'),'2025','v1.2',46.91,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',38,'wdc_position',15,'theoretical_max_points',648,'race_sprint_points',46.91,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='lance-stroll'),'2025','v1.2',40.74,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',33,'wdc_position',16,'theoretical_max_points',648,'race_sprint_points',40.74,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='yuki-tsunoda'),'2025','v1.2',40.74,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',33,'wdc_position',17,'theoretical_max_points',648,'race_sprint_points',40.74,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='pierre-gasly'),'2025','v1.2',27.16,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',22,'wdc_position',18,'theoretical_max_points',648,'race_sprint_points',27.16,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='gabriel-bortoleto'),'2025','v1.2',23.46,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',19,'wdc_position',19,'theoretical_max_points',648,'race_sprint_points',23.46,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='franco-colapinto'),'2025','v1.2',0,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',0,'wdc_position',20,'theoretical_max_points',648,'race_sprint_points',0,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='jack-doohan'),'2025','v1.2',0,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('fia_points',0,'wdc_position',21,'theoretical_max_points',648,'race_sprint_points',0,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='arvid-lindblad'),'2025','v1.2',0,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('participated',false,'fia_points',0,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='valtteri-bottas'),'2025','v1.2',0,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('participated',false,'fia_points',0,'wdc_placement_points',0,'champion_bonus',0)),
((select id from public.assets where sport='F1' and external_key='sergio-perez'),'2025','v1.2',0,null,'https://www.fia.com/events/fia-formula-one-world-championship/season-2025/2025-classifications',jsonb_build_object('participated',false,'fia_points',0,'wdc_placement_points',0,'champion_bonus',0))
on conflict (asset_id,season_label,scoring_version) do update
set points=excluded.points,source_ref=excluded.source_ref,breakdown=excluded.breakdown,updated_at=now();

with ranked as (
  select ass.id stat_id,rank() over(order by ass.points desc)::int calculated_rank
  from public.asset_season_stats ass
  join public.assets a on a.id=ass.asset_id
  where a.sport='F1' and ass.season_label='2025' and ass.scoring_version='v1.2'
)
update public.asset_season_stats ass
set rank=ranked.calculated_rank,updated_at=now()
from ranked where ranked.stat_id=ass.id;
