-- 027_nba_2025_26_historical_scores.sql
-- Overall placement ranks use regular-season wins, with Basketball-Reference SRS as deterministic tie-break.
insert into public.asset_season_stats(asset_id,season_label,scoring_version,points,rank,source_ref,breakdown)
values
((select id from public.assets where sport='NBA' and external_key='oklahoma-city-thunder'),'2025-26','v1.2',576.07,1,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',64,'regular_season_win_points',228.57,'overall_rank',1,'placement_points',150,'playoff_wins',11,'playoff_win_points',137.5,'advancement_points',60,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='san-antonio-spurs'),'2025-26','v1.2',623.93,2,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',62,'regular_season_win_points',221.43,'overall_rank',2,'placement_points',140,'playoff_wins',13,'playoff_win_points',162.5,'advancement_points',100,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='detroit-pistons'),'2025-26','v1.2',456.79,3,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',60,'regular_season_win_points',214.29,'overall_rank',3,'placement_points',130,'playoff_wins',7,'playoff_win_points',87.5,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='boston-celtics'),'2025-26','v1.2',357.5,4,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',56,'regular_season_win_points',200,'overall_rank',4,'placement_points',120,'playoff_wins',3,'playoff_win_points',37.5,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='denver-nuggets'),'2025-26','v1.2',327.86,5,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',54,'regular_season_win_points',192.86,'overall_rank',5,'placement_points',110,'playoff_wins',2,'playoff_win_points',25,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='new-york-knicks'),'2025-26','v1.2',889.29,6,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',53,'regular_season_win_points',189.29,'overall_rank',6,'placement_points',100,'playoff_wins',16,'playoff_win_points',200,'advancement_points',150,'championship_points',250,'champion',true,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='los-angeles-lakers'),'2025-26','v1.2',354.29,7,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',53,'regular_season_win_points',189.29,'overall_rank',7,'placement_points',90,'playoff_wins',4,'playoff_win_points',50,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='houston-rockets'),'2025-26','v1.2',290.71,8,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',52,'regular_season_win_points',185.71,'overall_rank',8,'placement_points',80,'playoff_wins',2,'playoff_win_points',25,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='cleveland-cavaliers'),'2025-26','v1.2',415.71,9,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',52,'regular_season_win_points',185.71,'overall_rank',9,'placement_points',70,'playoff_wins',8,'playoff_win_points',100,'advancement_points',60,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='minnesota-timberwolves'),'2025-26','v1.2',335,10,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',49,'regular_season_win_points',175,'overall_rank',10,'placement_points',60,'playoff_wins',6,'playoff_win_points',75,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='toronto-raptors'),'2025-26','v1.2',251.79,11,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',46,'regular_season_win_points',164.29,'overall_rank',11,'placement_points',50,'playoff_wins',3,'playoff_win_points',37.5,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='atlanta-hawks'),'2025-26','v1.2',229.29,12,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',46,'regular_season_win_points',164.29,'overall_rank',12,'placement_points',40,'playoff_wins',2,'playoff_win_points',25,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='phoenix-suns'),'2025-26','v1.2',190.71,13,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',45,'regular_season_win_points',160.71,'overall_rank',13,'placement_points',30,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='orlando-magic'),'2025-26','v1.2',218.21,14,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',45,'regular_season_win_points',160.71,'overall_rank',14,'placement_points',20,'playoff_wins',3,'playoff_win_points',37.5,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='philadelphia-76ers'),'2025-26','v1.2',245.71,15,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',45,'regular_season_win_points',160.71,'overall_rank',15,'placement_points',10,'playoff_wins',4,'playoff_win_points',50,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='charlotte-hornets'),'2025-26','v1.2',157.14,16,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',44,'regular_season_win_points',157.14,'overall_rank',16,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='miami-heat'),'2025-26','v1.2',153.57,17,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',43,'regular_season_win_points',153.57,'overall_rank',17,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='la-clippers'),'2025-26','v1.2',150,18,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',42,'regular_season_win_points',150,'overall_rank',18,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='portland-trail-blazers'),'2025-26','v1.2',162.5,19,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',42,'regular_season_win_points',150,'overall_rank',19,'placement_points',0,'playoff_wins',1,'playoff_win_points',12.5,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='golden-state-warriors'),'2025-26','v1.2',132.14,20,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',37,'regular_season_win_points',132.14,'overall_rank',20,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='milwaukee-bucks'),'2025-26','v1.2',114.29,21,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',32,'regular_season_win_points',114.29,'overall_rank',21,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='chicago-bulls'),'2025-26','v1.2',110.71,22,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',31,'regular_season_win_points',110.71,'overall_rank',22,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='new-orleans-pelicans'),'2025-26','v1.2',92.86,23,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',26,'regular_season_win_points',92.86,'overall_rank',23,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='dallas-mavericks'),'2025-26','v1.2',92.86,24,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',26,'regular_season_win_points',92.86,'overall_rank',24,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='memphis-grizzlies'),'2025-26','v1.2',89.29,25,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',25,'regular_season_win_points',89.29,'overall_rank',25,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='utah-jazz'),'2025-26','v1.2',78.57,26,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',22,'regular_season_win_points',78.57,'overall_rank',26,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='sacramento-kings'),'2025-26','v1.2',78.57,27,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',22,'regular_season_win_points',78.57,'overall_rank',27,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='brooklyn-nets'),'2025-26','v1.2',71.43,28,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',20,'regular_season_win_points',71.43,'overall_rank',28,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='indiana-pacers'),'2025-26','v1.2',67.86,29,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',19,'regular_season_win_points',67.86,'overall_rank',29,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS')),
((select id from public.assets where sport='NBA' and external_key='washington-wizards'),'2025-26','v1.2',60.71,30,'https://www.basketball-reference.com/leagues/NBA_2026.html',jsonb_build_object('regular_season_wins',17,'regular_season_win_points',60.71,'overall_rank',30,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','SRS'))
on conflict (asset_id,season_label,scoring_version) do update
set points=excluded.points,rank=excluded.rank,source_ref=excluded.source_ref,breakdown=excluded.breakdown,updated_at=now();
