-- 028_nfl_2025_historical_scores.sql
-- Overall placement ranks use regular-season winning percentage, then NFL net points as tie-break.
insert into public.asset_season_stats(asset_id,season_label,scoring_version,points,rank,source_ref,breakdown)
values
((select id from public.assets where sport='NFL' and external_key='seattle-seahawks'),'2025','v1.2',933.33,1,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',14,'regular_season_win_points',233.33,'overall_rank',1,'placement_points',150,'playoff_wins',3,'playoff_win_points',150,'advancement_points',150,'championship_points',250,'champion',true,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='new-england-patriots'),'2025','v1.2',624,2,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',14,'regular_season_win_points',233.33,'overall_rank',2,'placement_points',140.67,'playoff_wins',3,'playoff_win_points',150,'advancement_points',100,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='denver-broncos'),'2025','v1.2',474.66,3,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',14,'regular_season_win_points',233.33,'overall_rank',3,'placement_points',131.33,'playoff_wins',1,'playoff_win_points',50,'advancement_points',60,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='jacksonville-jaguars'),'2025','v1.2',338.67,4,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',13,'regular_season_win_points',216.67,'overall_rank',4,'placement_points',122,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='los-angeles-rams'),'2025','v1.2',472.67,5,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',12,'regular_season_win_points',200,'overall_rank',5,'placement_points',112.67,'playoff_wins',2,'playoff_win_points',100,'advancement_points',60,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='buffalo-bills'),'2025','v1.2',378.33,6,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',12,'regular_season_win_points',200,'overall_rank',6,'placement_points',103.33,'playoff_wins',1,'playoff_win_points',50,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='houston-texans'),'2025','v1.2',369,7,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',12,'regular_season_win_points',200,'overall_rank',7,'placement_points',94,'playoff_wins',1,'playoff_win_points',50,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='san-francisco-49ers'),'2025','v1.2',359.67,8,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',12,'regular_season_win_points',200,'overall_rank',8,'placement_points',84.67,'playoff_wins',1,'playoff_win_points',50,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='philadelphia-eagles'),'2025','v1.2',258.66,9,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',11,'regular_season_win_points',183.33,'overall_rank',9,'placement_points',75.33,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='los-angeles-chargers'),'2025','v1.2',249.33,10,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',11,'regular_season_win_points',183.33,'overall_rank',10,'placement_points',66,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='chicago-bears'),'2025','v1.2',315,11,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',11,'regular_season_win_points',183.33,'overall_rank',11,'placement_points',56.67,'playoff_wins',1,'playoff_win_points',50,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='pittsburgh-steelers'),'2025','v1.2',214,12,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',10,'regular_season_win_points',166.67,'overall_rank',12,'placement_points',47.33,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='green-bay-packers'),'2025','v1.2',188,13,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',9,'regular_season_win_points',150,'overall_rank',13,'placement_points',38,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='detroit-lions'),'2025','v1.2',178.67,14,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',9,'regular_season_win_points',150,'overall_rank',14,'placement_points',28.67,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='minnesota-vikings'),'2025','v1.2',169.33,15,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',9,'regular_season_win_points',150,'overall_rank',15,'placement_points',19.33,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='indianapolis-colts'),'2025','v1.2',143.33,16,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',8,'regular_season_win_points',133.33,'overall_rank',16,'placement_points',10,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='baltimore-ravens'),'2025','v1.2',133.33,17,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',8,'regular_season_win_points',133.33,'overall_rank',17,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='tampa-bay-buccaneers'),'2025','v1.2',133.33,18,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',8,'regular_season_win_points',133.33,'overall_rank',18,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='atlanta-falcons'),'2025','v1.2',133.33,19,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',8,'regular_season_win_points',133.33,'overall_rank',19,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='carolina-panthers'),'2025','v1.2',133.33,20,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',8,'regular_season_win_points',133.33,'overall_rank',20,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='dallas-cowboys'),'2025','v1.2',116.67,21,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',7,'regular_season_win_points',116.67,'overall_rank',21,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='miami-dolphins'),'2025','v1.2',116.67,22,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',7,'regular_season_win_points',116.67,'overall_rank',22,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='kansas-city-chiefs'),'2025','v1.2',100,23,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',6,'regular_season_win_points',100,'overall_rank',23,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='new-orleans-saints'),'2025','v1.2',100,24,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',6,'regular_season_win_points',100,'overall_rank',24,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='cincinnati-bengals'),'2025','v1.2',100,25,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',6,'regular_season_win_points',100,'overall_rank',25,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='washington-commanders'),'2025','v1.2',83.33,26,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',5,'regular_season_win_points',83.33,'overall_rank',26,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='cleveland-browns'),'2025','v1.2',83.33,27,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',5,'regular_season_win_points',83.33,'overall_rank',27,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='new-york-giants'),'2025','v1.2',66.67,28,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',4,'regular_season_win_points',66.67,'overall_rank',28,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='arizona-cardinals'),'2025','v1.2',50,29,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',3,'regular_season_win_points',50,'overall_rank',29,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='las-vegas-raiders'),'2025','v1.2',50,30,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',3,'regular_season_win_points',50,'overall_rank',30,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='tennessee-titans'),'2025','v1.2',50,31,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',3,'regular_season_win_points',50,'overall_rank',31,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points')),
((select id from public.assets where sport='NFL' and external_key='new-york-jets'),'2025','v1.2',50,32,'https://www.nfl.com/standings/league/2025/REG',jsonb_build_object('regular_season_wins',3,'regular_season_win_points',50,'overall_rank',32,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','net_points'))
on conflict (asset_id,season_label,scoring_version) do update
set points=excluded.points,rank=excluded.rank,source_ref=excluded.source_ref,breakdown=excluded.breakdown,updated_at=now();
