-- 029_mlb_2025_historical_scores.sql
-- Overall placement ranks use regular-season wins, then run differential as deterministic tie-break.
insert into public.asset_season_stats(asset_id,season_label,scoring_version,points,rank,source_ref,breakdown)
values
((select id from public.assets where sport='MLB' and external_key='milwaukee-brewers'),'2025','v1.2',476.6,1,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',97,'regular_season_win_points',220.45,'overall_rank',1,'placement_points',150,'playoff_wins',3,'playoff_win_points',46.15,'advancement_points',60,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='philadelphia-phillies'),'2025','v1.2',398.56,2,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',96,'regular_season_win_points',218.18,'overall_rank',2,'placement_points',140,'playoff_wins',1,'playoff_win_points',15.38,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='new-york-yankees'),'2025','v1.2',414.79,3,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',94,'regular_season_win_points',213.64,'overall_rank',3,'placement_points',130,'playoff_wins',3,'playoff_win_points',46.15,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='toronto-blue-jays'),'2025','v1.2',587.49,4,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',94,'regular_season_win_points',213.64,'overall_rank',4,'placement_points',120,'playoff_wins',10,'playoff_win_points',153.85,'advancement_points',100,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='los-angeles-dodgers'),'2025','v1.2',921.36,5,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',93,'regular_season_win_points',211.36,'overall_rank',5,'placement_points',110,'playoff_wins',13,'playoff_win_points',200,'advancement_points',150,'championship_points',250,'champion',true,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='chicago-cubs'),'2025','v1.2',395.63,6,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',92,'regular_season_win_points',209.09,'overall_rank',6,'placement_points',100,'playoff_wins',4,'playoff_win_points',61.54,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='san-diego-padres'),'2025','v1.2',309.93,7,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',90,'regular_season_win_points',204.55,'overall_rank',7,'placement_points',90,'playoff_wins',1,'playoff_win_points',15.38,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='seattle-mariners'),'2025','v1.2',436.86,8,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',90,'regular_season_win_points',204.55,'overall_rank',8,'placement_points',80,'playoff_wins',6,'playoff_win_points',92.31,'advancement_points',60,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='boston-red-sox'),'2025','v1.2',287.65,9,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',89,'regular_season_win_points',202.27,'overall_rank',9,'placement_points',70,'playoff_wins',1,'playoff_win_points',15.38,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='cleveland-guardians'),'2025','v1.2',275.38,10,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',88,'regular_season_win_points',200,'overall_rank',10,'placement_points',60,'playoff_wins',1,'playoff_win_points',15.38,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='detroit-tigers'),'2025','v1.2',334.27,11,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',87,'regular_season_win_points',197.73,'overall_rank',11,'placement_points',50,'playoff_wins',4,'playoff_win_points',61.54,'advancement_points',25,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='houston-astros'),'2025','v1.2',237.73,12,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',87,'regular_season_win_points',197.73,'overall_rank',12,'placement_points',40,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='new-york-mets'),'2025','v1.2',218.64,13,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',83,'regular_season_win_points',188.64,'overall_rank',13,'placement_points',30,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='cincinnati-reds'),'2025','v1.2',208.64,14,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',83,'regular_season_win_points',188.64,'overall_rank',14,'placement_points',20,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='kansas-city-royals'),'2025','v1.2',196.36,15,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',82,'regular_season_win_points',186.36,'overall_rank',15,'placement_points',10,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='texas-rangers'),'2025','v1.2',184.09,16,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',81,'regular_season_win_points',184.09,'overall_rank',16,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='san-francisco-giants'),'2025','v1.2',184.09,17,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',81,'regular_season_win_points',184.09,'overall_rank',17,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='arizona-diamondbacks'),'2025','v1.2',181.82,18,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',80,'regular_season_win_points',181.82,'overall_rank',18,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='miami-marlins'),'2025','v1.2',179.55,19,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',79,'regular_season_win_points',179.55,'overall_rank',19,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='st-louis-cardinals'),'2025','v1.2',177.27,20,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',78,'regular_season_win_points',177.27,'overall_rank',20,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='tampa-bay-rays'),'2025','v1.2',175,21,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',77,'regular_season_win_points',175,'overall_rank',21,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='atlanta-braves'),'2025','v1.2',172.73,22,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',76,'regular_season_win_points',172.73,'overall_rank',22,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='athletics'),'2025','v1.2',172.73,23,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',76,'regular_season_win_points',172.73,'overall_rank',23,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='baltimore-orioles'),'2025','v1.2',170.45,24,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',75,'regular_season_win_points',170.45,'overall_rank',24,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='los-angeles-angels'),'2025','v1.2',163.64,25,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',72,'regular_season_win_points',163.64,'overall_rank',25,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='pittsburgh-pirates'),'2025','v1.2',161.36,26,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',71,'regular_season_win_points',161.36,'overall_rank',26,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='minnesota-twins'),'2025','v1.2',159.09,27,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',70,'regular_season_win_points',159.09,'overall_rank',27,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='washington-nationals'),'2025','v1.2',150,28,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',66,'regular_season_win_points',150,'overall_rank',28,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='chicago-white-sox'),'2025','v1.2',136.36,29,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',60,'regular_season_win_points',136.36,'overall_rank',29,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential')),
((select id from public.assets where sport='MLB' and external_key='colorado-rockies'),'2025','v1.2',97.73,30,'https://www.mlb.com/standings/league/2025',jsonb_build_object('regular_season_wins',43,'regular_season_win_points',97.73,'overall_rank',30,'placement_points',0,'playoff_wins',0,'playoff_win_points',0,'advancement_points',0,'championship_points',0,'champion',false,'ranking_tiebreak','run_differential'))
on conflict (asset_id,season_label,scoring_version) do update
set points=excluded.points,rank=excluded.rank,source_ref=excluded.source_ref,breakdown=excluded.breakdown,updated_at=now();
