-- 030_ucl_2025_26_historical_scores.sql
insert into public.asset_season_stats(asset_id,season_label,scoring_version,points,rank,source_ref,breakdown)
values
((select id from public.assets where sport='UCL' and external_key='arsenal'),'2025-26','v1.2',607.14,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',1,'league_phase_wins',8,'league_phase_draws',0,'league_phase_match_points',200,'placement_points',100,'knockout_match_wins',3,'knockout_match_win_points',107.14,'advancement_points',200,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='bayern-munich'),'2025-26','v1.2',527.86,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',2,'league_phase_wins',7,'league_phase_draws',0,'league_phase_match_points',175,'placement_points',95,'knockout_match_wins',4,'knockout_match_win_points',142.86,'advancement_points',115,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='liverpool'),'2025-26','v1.2',325.71,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',3,'league_phase_wins',6,'league_phase_draws',0,'league_phase_match_points',150,'placement_points',90,'knockout_match_wins',1,'knockout_match_win_points',35.71,'advancement_points',50,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='tottenham-hotspur'),'2025-26','v1.2',265.71,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',4,'league_phase_wins',5,'league_phase_draws',2,'league_phase_match_points',145,'placement_points',85,'knockout_match_wins',1,'knockout_match_win_points',35.71,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='barcelona'),'2025-26','v1.2',331.43,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',5,'league_phase_wins',5,'league_phase_draws',1,'league_phase_match_points',135,'placement_points',75,'knockout_match_wins',2,'knockout_match_win_points',71.43,'advancement_points',50,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='chelsea'),'2025-26','v1.2',210,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',6,'league_phase_wins',5,'league_phase_draws',1,'league_phase_match_points',135,'placement_points',75,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='sporting-cp'),'2025-26','v1.2',295.71,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',7,'league_phase_wins',5,'league_phase_draws',1,'league_phase_match_points',135,'placement_points',75,'knockout_match_wins',1,'knockout_match_win_points',35.71,'advancement_points',50,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='manchester-city'),'2025-26','v1.2',210,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',8,'league_phase_wins',5,'league_phase_draws',1,'league_phase_match_points',135,'placement_points',75,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='real-madrid'),'2025-26','v1.2',377.86,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',9,'league_phase_wins',5,'league_phase_draws',0,'league_phase_match_points',125,'placement_points',60,'knockout_match_wins',4,'knockout_match_win_points',142.86,'advancement_points',50,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='inter-milan'),'2025-26','v1.2',185,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',10,'league_phase_wins',5,'league_phase_draws',0,'league_phase_match_points',125,'placement_points',60,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='paris-saint-germain'),'2025-26','v1.2',844.29,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',11,'league_phase_wins',4,'league_phase_draws',2,'league_phase_match_points',120,'placement_points',60,'knockout_match_wins',6,'knockout_match_win_points',214.29,'advancement_points',200,'championship_points',250,'champion',true)),
((select id from public.assets where sport='UCL' and external_key='newcastle-united'),'2025-26','v1.2',251.43,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',12,'league_phase_wins',4,'league_phase_draws',2,'league_phase_match_points',120,'placement_points',60,'knockout_match_wins',2,'knockout_match_win_points',71.43,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='juventus'),'2025-26','v1.2',195.71,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',13,'league_phase_wins',3,'league_phase_draws',4,'league_phase_match_points',115,'placement_points',45,'knockout_match_wins',1,'knockout_match_win_points',35.71,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='atletico-madrid'),'2025-26','v1.2',377.14,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',14,'league_phase_wins',4,'league_phase_draws',1,'league_phase_match_points',110,'placement_points',45,'knockout_match_wins',3,'knockout_match_win_points',107.14,'advancement_points',115,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='atalanta'),'2025-26','v1.2',190.71,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',15,'league_phase_wins',4,'league_phase_draws',1,'league_phase_match_points',110,'placement_points',45,'knockout_match_wins',1,'knockout_match_win_points',35.71,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='bayer-leverkusen'),'2025-26','v1.2',185.71,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',16,'league_phase_wins',3,'league_phase_draws',3,'league_phase_match_points',105,'placement_points',45,'knockout_match_wins',1,'knockout_match_win_points',35.71,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='borussia-dortmund'),'2025-26','v1.2',160.71,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',17,'league_phase_wins',3,'league_phase_draws',2,'league_phase_match_points',95,'placement_points',30,'knockout_match_wins',1,'knockout_match_win_points',35.71,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='olympiacos'),'2025-26','v1.2',125,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',18,'league_phase_wins',3,'league_phase_draws',2,'league_phase_match_points',95,'placement_points',30,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='club-brugge'),'2025-26','v1.2',115,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',19,'league_phase_wins',3,'league_phase_draws',1,'league_phase_match_points',85,'placement_points',30,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='galatasaray'),'2025-26','v1.2',186.43,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',20,'league_phase_wins',3,'league_phase_draws',1,'league_phase_match_points',85,'placement_points',30,'knockout_match_wins',2,'knockout_match_win_points',71.43,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='monaco'),'2025-26','v1.2',105,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',21,'league_phase_wins',2,'league_phase_draws',4,'league_phase_match_points',90,'placement_points',15,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='qarabag'),'2025-26','v1.2',100,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',22,'league_phase_wins',3,'league_phase_draws',1,'league_phase_match_points',85,'placement_points',15,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='bod-glimt'),'2025-26','v1.2',202.14,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',23,'league_phase_wins',2,'league_phase_draws',3,'league_phase_match_points',80,'placement_points',15,'knockout_match_wins',3,'knockout_match_win_points',107.14,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='benfica'),'2025-26','v1.2',90,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',24,'league_phase_wins',3,'league_phase_draws',0,'league_phase_match_points',75,'placement_points',15,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='marseille'),'2025-26','v1.2',75,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',25,'league_phase_wins',3,'league_phase_draws',0,'league_phase_match_points',75,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='pafos'),'2025-26','v1.2',80,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',26,'league_phase_wins',2,'league_phase_draws',3,'league_phase_match_points',80,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='union-saint-gilloise'),'2025-26','v1.2',75,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',27,'league_phase_wins',3,'league_phase_draws',0,'league_phase_match_points',75,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='psv-eindhoven'),'2025-26','v1.2',70,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',28,'league_phase_wins',2,'league_phase_draws',2,'league_phase_match_points',70,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='athletic-club'),'2025-26','v1.2',70,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',29,'league_phase_wins',2,'league_phase_draws',2,'league_phase_match_points',70,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='napoli'),'2025-26','v1.2',70,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',30,'league_phase_wins',2,'league_phase_draws',2,'league_phase_match_points',70,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='copenhagen'),'2025-26','v1.2',70,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',31,'league_phase_wins',2,'league_phase_draws',2,'league_phase_match_points',70,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='ajax'),'2025-26','v1.2',50,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',32,'league_phase_wins',2,'league_phase_draws',0,'league_phase_match_points',50,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='eintracht-frankfurt'),'2025-26','v1.2',35,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',33,'league_phase_wins',1,'league_phase_draws',1,'league_phase_match_points',35,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='slavia-prague'),'2025-26','v1.2',30,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',34,'league_phase_wins',0,'league_phase_draws',3,'league_phase_match_points',30,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='villarreal'),'2025-26','v1.2',10,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',35,'league_phase_wins',0,'league_phase_draws',1,'league_phase_match_points',10,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false)),
((select id from public.assets where sport='UCL' and external_key='kairat-almaty'),'2025-26','v1.2',10,null,'https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--champions-league-2025-26-all-the-results/',jsonb_build_object('league_phase_finish',36,'league_phase_wins',0,'league_phase_draws',1,'league_phase_match_points',10,'placement_points',0,'knockout_match_wins',0,'knockout_match_win_points',0,'advancement_points',0,'championship_points',0,'champion',false))
on conflict (asset_id,season_label,scoring_version) do update
set points=excluded.points,source_ref=excluded.source_ref,breakdown=excluded.breakdown,updated_at=now();

with ranked as (
  select ass.id stat_id,rank() over(order by ass.points desc)::int calculated_rank
  from public.asset_season_stats ass
  join public.assets a on a.id=ass.asset_id
  where a.sport='UCL' and ass.season_label='2025-26' and ass.scoring_version='v1.2'
)
update public.asset_season_stats ass
set rank=ranked.calculated_rank,updated_at=now()
from ranked where ranked.stat_id=ass.id;
