import { createSeedState } from '../domain/seed.js';
import { ACTIVE_SLOTS, KEEPER_SLOTS, LINEUP_STATUS, ROSTER_SIZE, TRADE_STATUS, DRAFT_STATUS } from '../domain/constants.js';
import { activeSlotCount, draftOrder, rosterForTeam } from '../domain/selectors.js';

const STORAGE_KEY='ten-sport-v0.3';
const clone=(v)=>structuredClone(v);
const now=()=>new Date().toISOString();

export class LocalLeagueService {
  constructor(){this.listeners=new Set();this.state=this.load();}
  load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return createSeedState();const parsed=JSON.parse(raw);return parsed.version===3?parsed:createSeedState();}catch{return createSeedState();}}
  persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(this.state));this.listeners.forEach(fn=>fn(this.getState()));}
  getState(){return clone(this.state);}
  subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn);}
  reset(){this.state=createSeedState();this.persist();}
  mutate(type,detail,fn){const next=clone(this.state);fn(next);next.transactionLog.unshift({id:crypto.randomUUID(),type,detail,createdAt:now()});this.state=next;this.persist();return this.getState();}
  renameTeam(teamId,name){const clean=name.trim();if(!clean)throw new Error('Team name cannot be empty.');return this.mutate('TEAM_RENAMED',{teamId,name:clean},s=>{const t=s.teams.find(x=>x.id===teamId);if(!t)throw new Error('Team not found.');t.name=clean;});}
  setLineupStatus(teamId,assetId,status){return this.mutate('LINEUP_CHANGED',{teamId,assetId,status},s=>{if(s.lockedAssetIds.includes(assetId))throw new Error('This asset is locked for its current scoring event.');const m=s.rosterMemberships.find(x=>x.teamId===teamId&&x.assetId===assetId);if(!m)throw new Error('Asset is not on this roster.');if(status===LINEUP_STATUS.ACTIVE&&m.lineupStatus!==LINEUP_STATUS.ACTIVE&&activeSlotCount(s,teamId)>=ACTIVE_SLOTS)throw new Error(`You can only have ${ACTIVE_SLOTS} active assets.`);m.lineupStatus=status;});}
  toggleKeeper(teamId,assetId){return this.mutate('KEEPER_CHANGED',{teamId,assetId},s=>{if(Date.now()>new Date(s.league.keeperDeadline).getTime())throw new Error('The keeper deadline has passed.');if(!s.rosterMemberships.some(m=>m.teamId===teamId&&m.assetId===assetId))throw new Error('Keeper must be on your roster.');const idx=s.keeperSelections.findIndex(k=>k.teamId===teamId&&k.assetId===assetId);if(idx>=0){s.keeperSelections.splice(idx,1);return;}const count=s.keeperSelections.filter(k=>k.teamId===teamId).length;if(count>=KEEPER_SLOTS)throw new Error(`You can only designate ${KEEPER_SLOTS} keepers.`);s.keeperSelections.push({teamId,assetId});});}
  acceptTrade(tradeId){return this.mutate('TRADE_ACCEPTED',{tradeId},s=>{const trade=s.trades.find(t=>t.id===tradeId);if(!trade||trade.status!==TRADE_STATUS.PENDING)throw new Error('Trade is no longer available.');const moveAsset=(assetId,from,to)=>{const m=s.rosterMemberships.find(x=>x.teamId===from&&x.assetId===assetId);if(!m)throw new Error('Trade validation failed: asset ownership changed.');m.teamId=to;m.lineupStatus=LINEUP_STATUS.BENCH;m.acquiredAt=now();s.keeperSelections=s.keeperSelections.filter(k=>k.assetId!==assetId);};const fromAssets=trade.items.filter(i=>i.side==='FROM'&&i.type==='ASSET');const toAssets=trade.items.filter(i=>i.side==='TO'&&i.type==='ASSET');const fromCount=rosterForTeam(s,trade.fromTeamId).length-fromAssets.length+toAssets.length;const toCount=rosterForTeam(s,trade.toTeamId).length-toAssets.length+fromAssets.length;if(fromCount>ROSTER_SIZE||toCount>ROSTER_SIZE)throw new Error('Trade would create an illegal roster size.');fromAssets.forEach(i=>moveAsset(i.assetId,trade.fromTeamId,trade.toTeamId));toAssets.forEach(i=>moveAsset(i.assetId,trade.toTeamId,trade.fromTeamId));const fillActive=(teamId,preferred)=>{let needed=Math.min(ACTIVE_SLOTS,rosterForTeam(s,teamId).length)-activeSlotCount(s,teamId);const ids=[...preferred,...rosterForTeam(s,teamId).filter(m=>m.lineupStatus===LINEUP_STATUS.BENCH).map(m=>m.assetId)];for(const id of ids){if(needed<=0)break;const m=s.rosterMemberships.find(x=>x.teamId===teamId&&x.assetId===id);if(m&&m.lineupStatus===LINEUP_STATUS.BENCH){m.lineupStatus=LINEUP_STATUS.ACTIVE;needed-=1;}}};fillActive(trade.toTeamId,fromAssets.map(i=>i.assetId));fillActive(trade.fromTeamId,toAssets.map(i=>i.assetId));trade.items.filter(i=>i.type==='DRAFT_PICK').forEach(i=>{const p=s.draftPicks.find(x=>x.id===i.draftPickId);if(!p)throw new Error('Draft pick not found.');const expected=i.side==='FROM'?trade.fromTeamId:trade.toTeamId;const destination=i.side==='FROM'?trade.toTeamId:trade.fromTeamId;if(p.currentTeamId!==expected)throw new Error('Trade validation failed: draft pick ownership changed.');p.currentTeamId=destination;});trade.status=TRADE_STATUS.ACCEPTED;trade.acceptedAt=now();});}
  declineTrade(tradeId){return this.mutate('TRADE_DECLINED',{tradeId},s=>{const t=s.trades.find(x=>x.id===tradeId);if(!t||t.status!==TRADE_STATUS.PENDING)throw new Error('Trade is no longer available.');t.status=TRADE_STATUS.DECLINED;});}
  setDraftStatus(status){return this.mutate('DRAFT_STATUS_CHANGED',{status},s=>{s.draft.status=status;});}
  makeDraftPick(assetId){return this.mutate('DRAFT_PICK_MADE',{assetId},s=>{if(s.draft.status!==DRAFT_STATUS.LIVE)throw new Error('Draft is not live.');if(s.draft.selections.some(x=>x.assetId===assetId))throw new Error('That asset has already been drafted.');const order=draftOrder(s);const slot=order[s.draft.currentOverallPick-1];if(!slot)throw new Error('Draft is complete.');const alreadyOwned=s.rosterMemberships.some(m=>m.assetId===assetId);if(alreadyOwned)throw new Error('That asset is already rostered.');s.draft.selections.push({id:crypto.randomUUID(),overallPick:s.draft.currentOverallPick,round:slot.round,teamId:slot.currentTeamId,assetId,createdAt:now()});s.rosterMemberships.push({id:crypto.randomUUID(),teamId:slot.currentTeamId,assetId,lineupStatus:LINEUP_STATUS.BENCH,acquiredAt:now()});s.draft.currentOverallPick+=1;if(s.draft.currentOverallPick>order.length)s.draft.status=DRAFT_STATUS.COMPLETE;});}
}
