import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
import React,{act} from 'react';
import { createRoot } from 'react-dom/client';
import { createRequire } from 'node:module';
import { createSeedState } from '../src/domain/seed.js';

test('My Team sorts active/bench separately, filters and watches assets, and persists keeper choices',async t=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost'});
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,IS_REACT_ACT_ENVIRONMENT:true});
 const state=structuredClone(createSeedState());state.assets.find(a=>a.id==='asset-20').pointsForTeam=9999;
 localStorage.setItem('ten-sport-v0.3',JSON.stringify(state));
 const bundle=await build({entryPoints:['src/App.jsx'],bundle:true,write:false,platform:'node',format:'cjs',external:['react','react-dom'],define:{'import.meta.env.VITE_SUPABASE_URL':'""','import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY':'""'}});
 let root;
 t.after(async()=>{await act(async()=>root?.unmount());dom.window.close();});
 const mount=async()=>{const module={exports:{}};new Function('require','module','exports',bundle.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(module.exports.default)));};
 const button=(text,scope=document)=>[...scope.querySelectorAll('button')].find(b=>b.textContent===text);
 const click=async node=>{assert.ok(node);assert.equal(node.disabled,false);await act(async()=>node.click());};
 const nav=async name=>click(button(name,document.querySelector('nav')));
 const rows=()=>[...document.querySelectorAll('.team-roster-table tbody tr')];
 const row=name=>rows().find(r=>r.querySelector('td:nth-child(3) b')?.textContent===name);
 const change=async(node,value)=>act(async()=>{node.value=value;node.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});
 const saved=()=>JSON.parse(localStorage.getItem('ten-sport-v0.3'));
 await mount();await nav('My Team');
 assert.equal(rows().length,20);assert.equal(rows()[15].querySelector('b').textContent,'Carlos Alcaraz');
 const verifyGroups=()=>{assert.ok(rows().slice(0,15).every(r=>r.querySelector('.lineup-position').textContent==='ACT'));assert.ok(rows().slice(15).every(r=>r.querySelector('.lineup-position').textContent==='BN'));};
 verifyGroups();
 await click([...document.querySelectorAll('.team-roster-table .sort-header')].find(b=>b.textContent.startsWith('Points For You')));
 verifyGroups();
 const points=rows().map(r=>Number(r.cells[4].textContent.replaceAll(',','')));
 assert.deepEqual(points.slice(0,15),points.slice(0,15).sort((a,b)=>a-b));assert.deepEqual(points.slice(15),points.slice(15).sort((a,b)=>a-b));
 await click([...document.querySelectorAll('.team-roster-table .sort-header')].find(b=>b.textContent.startsWith('Asset')));verifyGroups();
 await click(document.querySelector('[aria-label="Watch Carlos Alcaraz"]'));
 await change(document.querySelector('[aria-label="Roster watch status"]'),'WATCHED');assert.equal(rows().length,1);assert.equal(rows()[0].querySelector('b').textContent,'Carlos Alcaraz');
 await change(document.querySelector('[aria-label="Roster watch status"]'),'ALL');
 await change(document.querySelector('[aria-label="Roster sport"]'),'F1');assert.equal(rows().length,2);assert.equal(rows()[0].querySelector('.lineup-position').textContent,'ACT');
 await change(document.querySelector('[aria-label="Roster sport"]'),'ALL');
 for(const name of ['Lando Norris','Rory McIlroy','Carlos Alcaraz'])await click(button('Designate',row(name)));
 assert.equal(saved().keeperDesignations.length,3);assert.ok(button('Designate',row('Max Verstappen')).disabled);
 await click(button('Keeper ✓',row('Rory McIlroy')));await click(button('Designate',row('Max Verstappen')));
 assert.equal(saved().keeperDesignations.length,3);
 await nav('Keepers');assert.ok(document.querySelector('h2').textContent.includes('3/3'));assert.equal([...document.querySelectorAll('button')].filter(b=>b.textContent==='Keeper ✓').length,3);
 await act(async()=>root.unmount());root=null;await mount();await nav('My Team');assert.equal([...document.querySelectorAll('.team-roster-table button')].filter(b=>b.textContent==='Keeper ✓').length,3);
});
